#!/usr/bin/env bash
# Build the engine and put it where the surface expects it.
#
# There was no script for this, and the deployed .wasm could not be
# regenerated by anyone including the person who built it. The filename
# carries a hash OF THE BYTES, which is what lets `_headers` cache the file
# for a year: a new build is a new URL, so a stale one can never be served.
# That only holds if the hash and the file are produced together, which is
# what this does.
set -euo pipefail
cd "$(dirname "$0")"

OUT=../instruments/phyllotaxis/build
CRATE=target/wasm32-unknown-unknown/release/phyllotaxis_wasm.wasm

cargo build --release --target wasm32-unknown-unknown -p phyllotaxis-wasm
HASH=$(sha256sum "$CRATE" | cut -c1-8)

rm -f "$OUT"/engine-*.wasm
cp "$CRATE" "$OUT/engine-$HASH.wasm"

# The surface names the file it loads; keep the two in step.
sed -i "s#\./build/engine-[0-9a-f]*\.wasm#./build/engine-$HASH.wasm#" \
  ../instruments/phyllotaxis/index.html

echo "engine-$HASH.wasm  ($(stat -c%s "$OUT/engine-$HASH.wasm") bytes)"
grep -n 'WASM_URL' ../instruments/phyllotaxis/index.html
